feat: Adding commit-msg hook

diff --git a/.githooks/commit-msg b/.githooks/commit-msg
--- a/.githooks/commit-msg
+++ b/.githooks/commit-msg
@@ -1,24 +1,21 @@
 #!/usr/bin/env bash
 
-echo "Checking commit-message format..."
+if [ -z "$1" ]; then
+	echo "Missing argument (commit message). Did you try to run this manually?"
+	exit 1
+fi
 
-## the first arg is the path to the git commit temporary file
-TEMPORARY_FILE_PATH=$1
+commitTitle="$(cat $1 | head -n1)"
 
-## get commit-message from the temporary file
-COMMIT_MSG=`head -n1 $TEMPORARY_FILE_PATH`
+# ignore merge requests
+if echo "$commitTitle" | grep -qE "Merge branch"; then
+	echo "Commit hook: ignoring branch merge"
+	exit 0
+fi
 
-## init regex to match commit-message format
-REGEX="^\[(hotfix|\w+\-[0-9]+)\]( \w+)+$"
-
-## checking commit-message format
-if ! [[ $COMMIT_MSG =~ $REGEX ]];then
-    echo -e "Your commit-message format is not valid:\n$COMMIT_MSG\n"
-    echo "Valid format examples:"
-    echo "[PSBO-123] My commit message"
-    echo "[hotfix] My commit message"
-    exit 1
-else
-    echo "Well done! Your commit-message is valid."
-    exit 0
+# check semantic versioning scheme
+if ! echo "$commitTitle" | grep -E '^(feat|fix|docs|style|refactor|perf|test|chore)\(?(?:\w+|\s|\-|_)?\)?:\s\w+'; then
+	echo "Your commit title did not follow semantic versioning: $commitTitle"
+	echo "Please see https://github.com/angular/angular.js/blob/master/DEVELOPERS.md#commit-message-format"
+	exit 1
 fi
